config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get  '/sobre',   to: 'static#about'
  get  '/contactos',   to: 'static#contacts'

  resources :users do
    member do
      get :following, :followers,:ofertas, :candidatos
    end
  end

  get 'signup', to: 'users#new'

  get '/entidades', to: 'users#index_entidades', as: 'index_entidades'
  get '/candidatos', to: 'users#index_candidatos', as: 'index_candidatos'
  get '/entidades_destaque', to: 'users#index_entidades_destaque', as: 'index_entidades_destaque'
  get '/candidatos_destaque', to: 'users#index_candidatos_destaque', as: 'index_candidatos_destaque'

  get '/novo_candidato' , to:'users#novo_candidato'
  post '/novo_candidato' , to:'users#create'
  
  get '/nova_entidade' , to:'users#nova_entidade'
  post '/nova_entidade' , to:'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/users/:id/edit', to: 'users#update'
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'

  resources :oferta
  post '/oferta/new', to: 'oferta#create'
  get '/ofertas', to: 'oferta#index', as: 'index_ofertas'
  get '/ofertas_destaque', to: 'oferta#index_destaque', as: 'index_ofertas_destaque'
  put '/ofertas/:id/mudar_estado', to: 'oferta#mudar_estado', as: 'oferta_estado'

  resources :relationships, only: [:create, :destroy]
  resources :oferta_relationships, only: [:create, :destroy]
  
  resources :noticias
  post '/noticias/new', to: 'noticias#create'
  delete '/noticias/:id', to: 'noticias#destroy', as: 'noticias_delete'
  get '/noticias', to: 'noticias#index', as: 'index_noticias'

  get '/backoffice' ,to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/noticias', to: 'backoffice#index_noticias'

  get '/backoffice/noticias/:id', to: 'backoffice#show_noticia', as: 'backoffice_show_noticia'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  
  get '/backoffice/noticias/:id/edit', to:'backoffice#edit_noticias', as: 'backoffice_edit_noticias'
  patch '/backoffice/noticias/:id/edit', to:'noticias#update', as: 'backoffice_update_noticias'

  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'


  resources :backoffice
  resources :newsletters
  resources :password_resets, only: [:new, :create, :edit, :update]
  

end

app/models/user.rb
class User < ApplicationRecord

    has_one_attached :foto
    has_one_attached :cv

    has_many :ofertum,dependent: :destroy

    #Seguir Entidades/Candidatos
    has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id",
    dependent: :destroy
    
    has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id",
    
    dependent: :destroy
    
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

    #Candidatar a ofertas
    has_many :ofertas_active_relationships, class_name: "OfertaRelationship",
           foreign_key: "candidato_id",
           dependent: :destroy

    has_many :ofertas_passive_relationships, class_name: "OfertaRelationship",
            foreign_key: "oferta_id",
            dependent: :destroy

    has_many :ofertas, through: :ofertas_active_relationships, source: :oferta
    has_many :candidatos, through: :ofertas_passive_relationships, source: :candidato

    attr_accessor :remember_token, :activation_token, :reset_token

    before_save { email.downcase! }

    attribute :activated, :boolean, default: true
    attribute :destaque, :boolean, default: false
    attribute :newsletter, :boolean, default: true

    validates :name, presence: true, length: { maximum: 50 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, on: :create
    validates :password, length: { minimum: 6 }, allow_blank:true ,on: :update

    validates :morada, presence: true, allow_nil: true

    validates :codigo_postal, presence: true, allow_nil: true, zipcode: {country_code: :pt}
    validates :localidade, presence: true, allow_nil: true
    validates :telefone, presence: true , length: {is: 9}, numericality: true , allow_nil: true
    validates :telemovel, presence: true,numericality: true, length:  {is: 9}, allow_nil: true
    validates_date :data_nascimento, presence: true, allow_nil: true,
                    on_or_before: lambda { Date.current }, message: "- Data inválida"
    validates :bilhete_identidade, presence: true, allow_nil: true
    validates :apresentacao, presence: true, allow_nil: true
    validates :situacao_profissional, presence: true, allow_nil: true

    validates :foto, content_type: { in: %w[image/jpeg image/gif image/png], message: "- Formato inválido (Deve ser .jpeg, .gif ou .png)" },
                      size: { less_than: 5.megabytes, message: "- Demasiado grande (até 5MB)" }

    validates :cv, content_type: { in: %w[application/pdf], message: "- Formato inválido (Deve ser .pdf)" },
                      size: { less_than: 5.megabytes, message: "- Demasiado grande (até 5MB)" }

    #Scopes
    scope :estado, -> (estado) { where(activated: estado)}
    scope :ativo, -> { where(activated: true)}
    scope :destaque, -> { where(destaque: true)}
    scope :entidade, -> { where(tipo: 'entidade')}
    scope :candidato, -> { where(tipo: 'candidato')}
    scope :search, -> (query) {where("name like ? OR apresentacao like ?","%#{query}%","%#{query}%")}
    scope :localidade, -> (loc) { where localidade: loc}
    scope :situacao_profissional, -> (sit) { where situacao_profissional: sit}
    scope :area_profissional, -> (area) { where area_profissional: area}
    scope :tipo, -> (t) { where tipo: t}
    scope :recebem_newsletter, -> { where(newsletter: true)}
    scope :criado_esta_semana, -> {where("created_at >= ?",Time.zone.now - 7.days)}


    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    def forget
      update_attribute(:remember_digest, nil)
    end

    def create_reset_digest
      self.reset_token = User.new_token
      update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
    end
    
    # Sends password reset email.
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end

    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end
    
    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def display_image
      foto.variant(resize_to_limit: [500, 500])
    end

    # Follows a user.
    def follow(other_user)
      following << other_user
    end
  
    # Unfollows a user.
    def unfollow(other_user)
      following.delete(other_user)
    end
  
    # Returns true if the current user is following the other user.
    def following?(other_user)
      following.include?(other_user)
    end

    #offer
    def follow_oferta(oferta)
      ofertas_active_relationships.create(oferta_id: oferta.id)
    end

    def unfollow_oferta(oferta)
      ofertas_active_relationships.find_by(oferta_id: oferta.id).destroy
    end

    def candidato_oferta?(oferta)
      ofertas.include?(oferta)
    end

  


    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
      SecureRandom.urlsafe_base64
    end

    class << self
        def digest(string)
          cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
              BCrypt::Engine.cost
          BCrypt::Password.create(string, cost: cost)
        end
    
        def new_token
          SecureRandom.urlsafe_base64
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :destroy,:edit_user,:edit_password]
  before_action :correct_user, only: [:edit, :update, :edit_user,:edit_password]
  before_action :admin_user, only: [:destroy]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @followers = @user.followers.paginate(page:params[:page], per_page:2)
    if @user.tipo == 'entidade'
        @ofertas = @user.ofertum.order(created_at: :desc)
        @ativas = @ofertas.ativa.paginate(page:params[:page], per_page:2)
        @historico = @ofertas.where(ativa: false).limit(2)
    else
      @candidaturas = @user.ofertas.ativa.paginate(page:params[:page], per_page:2)
    end
  end
  
  def create
    @user = User.new(user_params)
    @user.foto.attach(params[:user][:foto])
    if @user.save
        if admin_user?(current_user) && @user!=current_user
          flash[:success] = "Utilizador criado com sucesso"
          redirect_to backoffice_users_path
        else
          log_in @user
          flash[:success] = "Bem-vindo à Bolsa de Emprego"
          redirect_to @user
        end
    else
      if admin_user?(current_user)
        render 'backoffice/new'
      else
        render(params[:user][:tipo] == 'entidade' ? 'users/nova_entidade' : 'users/novo_candidato', :user => @user)
      end
    end
  end

  def novo_candidato
    @user = User.new
  end

  def nova_entidade
    @user = User.new
  end

  def index_candidatos
    @users = User.ativo.candidato.order(created_at: :desc)
    filtering_params(params).each do |key, value|
      @users = @users.public_send(key,value) if value.present?
    end
    @users = @users.paginate(page: params[:page], per_page:8)
  end

  def index_candidatos_destaque
    @users = User.ativo.candidato.destaque.order(created_at: :desc)
    filtering_params(params).each do |key, value|
      @users = @users.public_send(key,value) if value.present?
    end
    @users = @users.paginate(page: params[:page], per_page:8)
    render 'index_candidatos'
  end

  def index_entidades
    @users = User.ativo.entidade.order(created_at: :desc)
    filtering_params(params).each do |key, value|
      @users = @users.public_send(key,value) if value.present?
    end
    @users = @users.paginate(page: params[:page], per_page:8)
  end

  def index_entidades_destaque
    @users = User.ativo.entidade.destaque.order(created_at: :desc)
    filtering_params(params).each do |key, value|
      @users = @users.public_send(key,value) if value.present?
    end
    @users = @users.paginate(page: params[:page], per_page:8)
    render 'index_entidades'
  end

  def edit
    @user = User.find(params[:id])
  end

  def edit_user
    @user = User.find(params[:id])
  end

  def edit_password
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if params[:user][:current_password].present?
      current_password = params[:user].delete(:current_password)
      user = @user.authenticate(current_password)

      if @user && user 
        if params[:user][:password] == params[:user][:password_confirmation] 
            if params[:user][:password].length>=6
              user.update_attribute(:password, params[:user][:password])
              flash[:success] = "Password Atualizada!"
              redirect_to admin_user?(current_user) ? backoffice_show_users_path(@user) : user_path(current_user.id)
            else
              flash[:danger] = "Password inválida"
              render 'edit_password'
            end

        else
          flash[:danger] = "Passwords não coincidem"
          render 'edit_password'
        end
      else
        flash[:danger] = "Password atual inválida"
        render 'edit_password'
      end

    else
      
      if @user.update_attributes(user_params)
        flash[:success] = "Perfil Atualizado!"
        redirect_to admin_user?(current_user)? backoffice_show_users_path(@user) : user_path(current_user.id)
      else
        render 'edit'
      end

    end

  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Utilizador apagado!"
    redirect_to backoffice_users_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :tipo, :morada, :codigo_postal, :localidade,
                                 :telefone, :telemovel, :pagina, :data_nascimento, :bilhete_identidade, :area_profissional, :apresentacao,
                                 :nivel_habilitacoes, :habilitacoes_literarias, :situacao_profissional, :experiencia_profissional,:activated,
                                 :foto,:cv,:newsletter,:destaque)
  end

  def filtering_params(params)
    params.slice(:search,:area_profissional,:situacao_profissional,:localidade)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_candidato_detalhe.html.erb
<aside class="col-md-2">
  <section class="col-md-12">
    <h1>
      <%= @user.name %>
    </h1>
  </section>

  <section class="col-md-12">
      <% if @user.foto.attached? %>
        <%= image_tag @user.display_image , style:'width:100%' %>
      <% else %>
        <%= image_tag 'default.png' , style:'width:100%' %>
      <% end %>
  </section>

  <section class="col-md-12" >
    <% if @user.cv.attached? %>
      <%= link_to "Currículo", @user.cv %>
    <% end %>
  </section>

  <section class="col-md-12" >
    <% if logged_in? && current_user.tipo == 'entidade'%>
        <%= render 'form_interesse' %>
    <% end %>
  </section>
</aside>

<% if current_user?(@user) || admin_user?(current_user) %>
  <aside class="col-md-4"> </aside>
  <aside class="col-md-6">
    <section>
      <%= link_to "Editar dados", edit_user_path(@user), class: 'btn btn-default' %>
      <%= link_to "Editar Password", edit_password_path(@user), class: 'btn btn-default' %>
    </section>
  </aside>
<% end %>



<aside class="col-md-10">
  <section class="user_edit">
    <p><b>Apresentação</b></p>
    <p> <%= raw @user.apresentacao %> </p>
    <p><b>Atividade Profissional</b></p>
    <p><%= @user.area_profissional %></p>
  </section>
  <section>
    <p><b>Morada</b></p>
    <p><%= @user.codigo_postal %> <%= @user.localidade %></p>
  </section>

  <section>
    <h3><strong>Dados Profissionais</strong></h3>
    <p><strong>Situação Profissional</strong></p>
    <p><%= @user.situacao_profissional %></p>
    <p><strong>Nível Habilitações</strong></p>
    <p><%= @user.nivel_habilitacoes %></p>
    <p><strong>Habilitações Literárias</strong></p>
    <p><%= raw @user.habilitacoes_literarias %></p>
    <p><strong>Experiência Profissional</strong></p>
    <p><%= raw @user.experiencia_profissional %></p>
  </section>

  <section>
    <p><b>Contactos</b></p>
    <p>Telemóvel: <%= @user.telemovel %> | Telefone: <%= @user.telefone%></p>
    <p><%= @user.email %></p>
    <p><%= link_to @user.pagina, "http://#{@user.pagina}" %><p>
  </section>
</aside>

app/views/users/_entidade.html.erb
<div class="row">
  <% if current_user?(@user) && params[:perfil] == 'true'%>
      <%= render 'entidade_perfil' %>
  <% else %>
      <%= render 'entidade_detalhe'  %>
  <% end %>
</div>

app/views/users/_entidade_detalhe.html.erb
<aside class="col-md-2">
  <section class="col-md-12">
    <h1>
      <%= @user.name %>
    </h1>
  </section>

  <section class="col-md-12">
      <% if @user.foto.attached? %>
        <%= image_tag @user.display_image , style:'width:100%' %>
      <% else %>
        <%= image_tag 'default.png' , style:'width:100%' %>
      <% end %>
  </section>

  <section class="col-md-12" >
    <% if logged_in? && current_user.tipo == 'candidato'%>
        <%= render 'form_interesse' %>
    <% end %>
  </section>
</aside>

<% if current_user?(@user) || admin_user?(current_user) %>
  <aside class="col-md-4"> </aside>
  <aside class="col-md-6">
    <section>
      <%= link_to "Editar dados", edit_user_path(@user), class: 'btn btn-default' %>
      <%= link_to "Editar Password", edit_password_path(@user), class: 'btn btn-default' %>
    </section>
  </aside>
<% end %>

<aside class="col-md-10">
  <section class="user_edit">
    <p> <%= raw @user.apresentacao %> </p>
    <p><b>Atividade Profissional</b></p>
    <p><%= @user.area_profissional %></p>
  </section>
  <section>
    <p><b>Morada</b></p>
    <p><%= raw @user.morada %></p>
    <p><%= @user.codigo_postal %> <%= @user.localidade %></p>
  </section>

  <section>
    <p><b>Contactos</b></p>
    <p>Telemóvel: <%= @user.telemovel %> | Telefone: <%= @user.telefone%></p>
    <p><%= @user.email %></p>
    <p><%= link_to @user.pagina, "http://#{@user.pagina}" %><p>
  </section>
</aside>

<aside class="col-md-12">
  <section class="col-md-6" >
    <h1> Ofertas ativas </h1>
    <% if @ativas.any? %>
      <%= render @ativas %>
    <% else %>
      <p>Não tem quaisquer ofertas activas.</p>
    <% end %>
  </section>
</aside>

app/views/users/_entidade_perfil.html.erb
<aside class="col-md-6">
  <section>
    <h1> Ofertas <%= link_to " (Inserir oferta) ", new_ofertum_path %> </h1>
    <% if @ativas.any? %>
        <%= render @ativas %>
        <%= will_paginate(@ativas)%>
    <% else %>
        <p>Não tem quaisquer ofertas activas.</p>
    <% end %>
  </section>

  <section>
    <h1> Histórico </h1>
    <%= render @historico %>
  </section>
</aside>

<aside class="col-md-6">
  <section>
    <%= link_to "Editar dados", edit_user_path(@user), class: 'btn btn-default' %>
    <%= link_to "Editar Password", edit_password_path(@user), class: 'btn btn-default' %>
  </section>

  <section>
    <h1> Candidatos Interessados </h1>
    <% if  @followers.any? %>
      <%= render @followers %>
    <% else %>
      <p>Sem candidatos interessados.</p>
    <% end %>
  </section>
</aside>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
    <div class="row">
        <%= hidden_field_tag :followed_id, @user.id %>
        <%= f.submit "Interessado/a", class: "btn btn-default" %>
    </div>

    
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Não interessado/a", class: "btn btn-default" %>
<% end %>

app/views/users/_user.html.erb
<aside>
  <section>
    <div class="col-md-3" >
      <% if user.foto.attached? %>
        <%= image_tag user.display_image , style:'width:100%' %>
      <% else %>
        <%= image_tag 'default.png' , style:'width:100%' %>
      <% end %>
    </div>
    <div class="col-md-9">
      <%= link_to user.name, user  %>
      <% if user.tipo == 'entidade' %>
          <p> <%= raw user.apresentacao.first(80) %></p>
      <% else %>
          <p><%= user.area_profissional %> <br><%= raw user.experiencia_profissional.first(45) %> <br><%= user.nivel_habilitacoes %></p>
      <% end %>
    </div>
  </section>
</aside>

app/views/users/edit.html.erb
<% provide(:title, 'Editar Utilizador') %>

<div class="row">
  <aside class="col-md-4">
    <h3>Editar Utilizador</h3>
  </aside>
</div>


<div class="row">
  <div class="col-md-12 ">
    <%= simple_form_for @user, html: {multipart: true}, url: edit_user_path do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div id="info_candidate" class="profile">
        <%= render 'layouts/form_info_pessoal', :f => f %>
        <div class="row">
            <% if @user.tipo == 'candidato' %>
                <div class="col-md-12">
                    <h3>Apresentação</h3>
                    <%= f.text_area :apresentacao, label:  "Apresentação", class:"tinymce" %>
                </div>
        
                <div class="col-md-2">
                    <%= f.date_field :data_nascimento, label: "Data de Nascimento" ,  class: 'form-control' %>
                </div>
            <% end %>

            <% if @user.tipo == 'entidade' %>
                <div class="col-md-2 ">
                    <%= f.input :bilhete_identidade, label: "NIF" %>
                </div>
            <% else %>
                <div class="col-md-3 col-md-offset-4">
                    <%= f.input :bilhete_identidade, label: "Nº do Cartão de Cidadão" %>
                </div>
            <% end %>
        </div>
        <hr>
        <div class="row">
            <% if @user.tipo == 'candidato' %>
                <%= render 'layouts/form_atividade', :f => f %>
            <% else %>
                <div class="col-md-2">
                    <%= f.input :area_profissional, label: "Atividade Profissional",collection: (['Informática','Educação','Saúde','Metalúrgica','Prestação de Serviços']) %>
                </div>

                <div class="col-md-12">
                    <%= f.text_area :apresentacao, label: "Apresentação", class:"tinymce" %>
                </div>
            <% end %>
        </div>

        <div class="row" style="margin:5% 0%">
            <div class="col-md-6">
                <div class="checkbox">
                    <%= f.input :newsletter, inline_label: "Receber Newsletter" %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <%= f.button :submit, 'Editar', class: 'btn btn-primary' %>
            </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, 'Editar Password') %>
<div class="row">
  <aside class="col-md-4">
    <h3>Editar Password</h3>
  </aside>
</div>

<%= simple_form_for @user, html: {multipart: true}  do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="row" id="login_candidate_info">
      <div class="col-md-6">
        <%= f.input :email %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :current_password, label: "Password Atual" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :password %>
      </div>
      <div class="col-md-6">
        <%= f.input :password_confirmation, label: "Confirmação Password" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= f.button :submit, 'Editar Password', class: 'btn btn-primary' %>
      </div>
    </div>
    <hr>
<% end %>

app/views/users/index_entidades.html.erb
<% provide(:title, 'Entidades') %>
<div class="row">
  <aside class="col-md-4">
    <h3>Entidades</h3>
  </aside>
</div>

<div class="row">
  <aside >
    <%= form_for index_entidades_path, method: 'get'  do  %>
        <div class="col-md-3">
          <%= text_field_tag :search, params[:search], placeholder: 'Pesquisa', class: 'form-control' %>
        </div>
        <div class="col-md-3">
          <% field_array = User.entidade.distinct.pluck(:area_profissional) %>
          <%= select_tag(:area_profissional,
                options_for_select(field_array,
                params[:area_profissional]),
                {include_blank: 'Área Profissional...', :onChange => "javascript: this.form.submit();", class: 'form-control'})  %>
        </div>
    
        <div class="col-md-3">
          <% field_array = User.entidade.distinct.pluck(:localidade) %>
          <%= select_tag(:localidade, 
                options_for_select(field_array,
                params[:localidade]),
                {include_blank: 'Localidade...', :onChange => "javascript: this.form.submit();", class: 'form-control'}) %>
        </div>
    <% end %>

  </aside>
</div>

<div class="row">
  <% @users.each do |user|  %>
      <div class="col-md-6">
        <%= render user %>
        <div class="col-md-8" style="min-height: 40px;">
          <% if logged_in? && current_user.tipo == 'candidato'  %>
            <% @user = user %>
            <%= render 'form_interesse' %>
          <% end %>
          <% if current_user?(user) || admin_user?(current_user) %>
              <div class="col-md-2">
                <%= link_to "Editar", edit_user_path(user), class: 'btn btn-default' %>
              </div>
          <% end %>
        </div>
      </div>
  <% end %>
</div>
<%= will_paginate(@users)%>

app/views/users/new.html.erb
<% provide(:title, 'Registo') %>
<h1>Novo Registo</h1>

<div class="row">
    <div class="col-md-6 center">
      <%= link_to "Novo Candidato",  novo_candidato_url ,class: 'btn btn-default btn-lg' %>
    </div>
    <div class="col-md-6 center">
      <%= link_to "Nova Entidade", nova_entidade_url ,class: 'btn btn-default btn-lg' %>
    </div>
</div>

app/views/users/nova_entidade.html.erb
<% provide(:title, 'Nova Entidade') %>
<h1>Nova Entidade</h1>

<div class="row">
  <%= render 'layouts/form_registo_entidade' %>
</div>

app/views/users/novo_candidato.html.erb
<% provide(:title, 'Novo Candidato') %>
<h1>Novo Candidato</h1>

<div class="row">
  <%= render 'layouts/form_registo_candidato' %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row profile">
  <%  if @user.tipo == 'entidade' %>
      <%= render 'entidade' %>
  <% elsif @user.tipo == 'candidato' %>
      <%= render 'candidato' %>
  <% end %>
</div>