config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get  '/sobre',   to: 'static#about'
  get  '/contactos',   to: 'static#contacts'

  resources :users do
    member do
      get :following, :followers,:ofertas, :candidatos
    end
  end

  get 'signup', to: 'users#new'

  get '/entidades', to: 'users#index_entidades', as: 'index_entidades'
  get '/candidatos', to: 'users#index_candidatos', as: 'index_candidatos'
  get '/entidades_destaque', to: 'users#index_entidades_destaque', as: 'index_entidades_destaque'
  get '/candidatos_destaque', to: 'users#index_candidatos_destaque', as: 'index_candidatos_destaque'

  get '/novo_candidato' , to:'users#novo_candidato'
  post '/novo_candidato' , to:'users#create'
  
  get '/nova_entidade' , to:'users#nova_entidade'
  post '/nova_entidade' , to:'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/users/:id/edit', to: 'users#update'
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'

  resources :oferta
  post '/oferta/new', to: 'oferta#create'
  get '/ofertas', to: 'oferta#index', as: 'index_ofertas'
  get '/ofertas_destaque', to: 'oferta#index_destaque', as: 'index_ofertas_destaque'
  put '/ofertas/:id/mudar_estado', to: 'oferta#mudar_estado', as: 'oferta_estado'

  resources :relationships, only: [:create, :destroy]
  resources :oferta_relationships, only: [:create, :destroy]
  
  resources :noticias
  post '/noticias/new', to: 'noticias#create'
  delete '/noticias/:id', to: 'noticias#destroy', as: 'noticias_delete'
  get '/noticias', to: 'noticias#index', as: 'index_noticias'

  get '/backoffice' ,to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/noticias', to: 'backoffice#index_noticias'

  get '/backoffice/noticias/:id', to: 'backoffice#show_noticia', as: 'backoffice_show_noticia'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  
  get '/backoffice/noticias/:id/edit', to:'backoffice#edit_noticias', as: 'backoffice_edit_noticias'
  patch '/backoffice/noticias/:id/edit', to:'noticias#update', as: 'backoffice_update_noticias'

  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'


  resources :backoffice
  resources :newsletters
  resources :password_resets, only: [:new, :create, :edit, :update]
  

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

    before_action :logged_in_user
    before_action :admin_user
    
    def show
    end

    def new
        @user = User.new
    end

    def home
        render 'backoffice/home'
    end
    
    def index_users
        @users = User.all.order(updated_at: :desc)
        @users = @users.tipo(params[:tipo]) if params[:tipo].present?
        @users = @users.estado(params[:ativo]) if params[:ativo].present?
        @users = @users.search(params[:search]) if params[:search].present?
        @users = @users.paginate(page: params[:page], per_page: 10)
    end

    def index_noticias
        @noticias = Noticia.all.order(updated_at: :desc)
        @noticias  = @noticias.titulo(params[:titulo]) if params[:titulo].present?
        @noticias = @noticias.paginate(page: params[:page], per_page: 10)
    end

    def show_noticia
        @noticia = Noticia.find(params[:id])
    end

    def show_users
        @user = User.find(params[:id])
    end

    def edit_users
        @user = User.find(params[:id])
    end

    def edit_user_password
        @user = User.find(params[:id])
    end

    def edit_noticias
        @noticia = Noticia.find(params[:id])
    end
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/views/backoffice/edit_noticias.html.erb
<% provide(:title, 'Editar') %>
<div class="row">
  <aside class="col-md-4">
    <h3>Editar</h3>
  </aside>
</div>
<div class="row">
  <div class="col-md-12 ">
    <%= render 'layouts/form_edicao_noticias' %>
  </div>
</div>

app/views/backoffice/edit_user_password.html.erb
<% provide(:title, 'Editar') %>
<div class="row">
  <aside class="col-md-4">
    <h3>Editar</h3>
  </aside>
</div>
<div class="row">
  <div class="col-md-12 ">
    <%= render 'layouts/form_edicao_password_backoffice' %>
  </div>
</div>

app/views/backoffice/edit_users.html.erb
<% provide(:title, 'Editar') %>

<div class="row">
  <aside class="col-md-4">
    <h3>Editar</h3>
  </aside>
</div>
<div class="row">
  <div class="col-md-12 ">
    <%= simple_form_for @user, url: backoffice_edit_users_path do |f| %>
        <%= render 'layouts/form_edicao_backoffice', :f => f %>
  <% end %>
  </div>
</div>

app/views/backoffice/index_noticias.html.erb
<div class="row">
  <aside>
    <section>
      <h3>
        Notícias
      </h3>
    </section>
  </aside>
</div>

<div class="row">
  <aside >
    <%= form_for backoffice_noticias_path, method:'get' do |f| %>
        <div class="col-md-3">
          <%= text_field_tag :titulo, params[:titulo], placeholder: 'Pesquisa',class:'form-control' %>
        </div>
    <% end %>
  </aside>
</div>
<div class="row table-responsive">
  <table class="table table-striped ">
    <tr>
      <th>Nome</th>
      <th>Data</th>
      <th>Destaque</th>
      <th>Activo</th>
      <th>Ações</th>
    </tr>
    <% @noticias.each do |news| %>
        <tr>
          <td><%= news.titulo %></td>
          <td><%= news.data %></td>
          <td><%= news.destaque %></td>
          <td><%= news.ativa %></td>
          <td>
            <%= link_to "Detalhe", backoffice_show_noticia_path(news), class: 'btn btn-info' %>
            <%= link_to "Editar", backoffice_edit_noticias_path(news) , class: 'btn btn-info' %>
            <%= link_to "Apagar", noticias_delete_path(news), method: :delete,
                            data: { confirm: "Tem a certeza que pretende eliminar esta notícia?" }, class: 'btn btn-danger' %>
        </tr>
    <% end %>

  </table>
</div>
<div class="row">
  <aside>
    <section>
      <%= link_to "Inserir", new_noticia_path, class: 'btn btn-default' %>
    </section>
  </aside>
</div>
<div class="row">
  <%= will_paginate(@noticias) %>
</div>

app/views/backoffice/index_users.html.erb
<div class="row">
  <aside >
    <section>
      <h3>Utilizadores</h3>
    </section>
  </aside>
</div>

<div class="row">
    <%= form_for backoffice_users_path,  method: 'get' do |f| %>
        <div class="col-md-3">
          <%= text_field_tag :search, params[:search], placeholder: 'Pesquisa',class:'form-control' %>
        </div>
        <div class="col-md-3">
          <%= select_tag(:tipo, options_for_select([['admin'],['candidato'],['entidade']], params[:tipo]),{ include_blank: 'Tipo...', :onChange => "javascript: this.form.submit();",class:'form-control'})  %>
        </div>
        <div class="col-md-3">
          <%= select_tag(:ativo, options_for_select([['true'],['false']], params[:ativo]),{ include_blank: 'Ativo...', :onChange => "javascript: this.form.submit();",class:'form-control'})  %>
        </div>
    <% end %>
</div>
<div id="users" class="row table-responsive">
    <table class="table table-striped">
      <tr>
        <th>Nome</th>
        <th>Tipo</th>
        <th>Ativo</th>
        <th >Ações</th>
      </tr>
      <% @users.each do |user| %>
          <tr>
            <td class="col-md-3"><%= user.name %></td>
            <td class="col-md-3"><%= user.tipo %></td>
            <td class="col-md-3"><%= user.activated %></td>
            <td class="col-md-3">
              <%= link_to "Detalhe", backoffice_show_users_path(user), class: 'btn btn-info' %>
              <%= link_to "Editar", backoffice_edit_users_path(user), class: 'btn btn-info' %>
              <%= link_to "Apagar", user, method: :delete,
                          data: { confirm: "Tem a certeza que pretende eliminar este utilizador?" }, class: 'btn btn-danger' %>
            </td>

          </tr>
      <% end %>
    </table>
</div>

<div class="row">
  <aside >
    <section>
      <%= link_to "Inserir", new_backoffice_path, class: 'btn btn-default' %>
    </section>
  </aside>
</div>

<div class="row">
  <aside>
    <section>
      <%= will_paginate(@users) %>
    </section>
  </aside>
</div>

app/views/backoffice/new.html.erb
<div class="row">
  <aside class="col-md-4">
    <h3>Inserir/Editar</h3>
  </aside>
</div>
<%= simple_form_for @user, url: new_backoffice_path do |f| %>
    <%= render 'shared/error_messages' %>
    <%= render 'layouts/form_registo_backoffice', :f => f %>
<% end %>

app/views/backoffice/show_noticia.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h3>Detalhe da Notícia</h3>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Título</strong></p>
      <p><%= @noticia.titulo %></p>
    </section>
  </aside>
  <aside class="col-md-6">
    <section>
      <p><strong>Data</strong></p>
      <p><%= @noticia.data %></p>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-12">
    <section>
      <p><strong>Sumário</strong></p>
      <p><%= raw @noticia.sumario %></p>
      <p><strong>Texto</strong></p>
      <p><%= raw @noticia.descricao %></p>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-2">
    <section>
        <h3> Imagem</h3>
        <% if @noticia.foto.attached? %>
            <%= image_tag @noticia.display_image , style:'width:100%' %>
        <% else %>
            <%= image_tag 'default_noticia.png' , style:'width:100%' %>
        <% end %>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Destaque</strong></p>
      <p><%= @noticia.destaque %></p>
    </section>
  </aside>
  <aside class="col-md-6">
    <section>
      <p><strong>Activa</strong></p>
      <p><%= @noticia.ativa %></p>
    </section>
  </aside>
</div>
<div class="row">
  <%= link_to "Editar", backoffice_edit_noticias_path(@noticia),class: 'btn btn-default' %>
  <%= link_to "Apagar", noticias_delete_path(@noticia), method: :delete,
                  data: { confirm: "Tem a certeza que pretende eliminar esta notícia?" }, class: 'btn btn-danger' %>
</div>
<div class="row" style="margin-top:2%;">
  <%= link_to "Inserir", new_noticia_path,class: 'btn btn-default' %>
  <%= link_to "Listagem", backoffice_noticias_url ,class: 'btn btn-default' %>
</div>

app/views/backoffice/show_users.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h3>Detalhe do Utilizador</h3>
    </section>
  </aside>
</div>
<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Nome</strong></p>
      <p><%= @user.name %></p>
    </section>
  </aside>
  <aside class="col-md-6">
    <section>
      <p><strong>Tipo</strong></p>
      <p><%= @user.tipo %></p>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Email</strong></p>
      <p><%= @user.email %></p>
    </section>
  </aside>

  <aside class="col-md-6">
    <section>
      <p><strong>Ativo</strong></p>
      <p><%= @user.activated %></p>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Destaque</strong></p>
      <p><%= @user.destaque %></p>
    </section>
  </aside>
</div>

<div class="row">
  <%= link_to "Editar", backoffice_edit_users_path(@user),class: 'btn btn-default' %>
  <%= link_to "Alterar Password", backoffice_edit_user_password_path(@user),class: 'btn btn-default' %>
  <%= link_to "Apagar", @user, method: :delete,
            data: { confirm: "Tem a certeza que pretende eliminar este utilizador?" }, class: 'btn btn-danger' %>
</div>

<div class="row" style="margin-top:2%;">
  <%= link_to "Inserir", new_backoffice_url,class: 'btn btn-default' %>
  <%= link_to "Listagem", backoffice_users_path ,class: 'btn btn-default' %>
</div>