config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get  '/sobre',   to: 'static#about'
  get  '/contactos',   to: 'static#contacts'

  resources :users do
    member do
      get :following, :followers,:ofertas, :candidatos
    end
  end

  get 'signup', to: 'users#new'

  get '/entidades', to: 'users#index_entidades', as: 'index_entidades'
  get '/candidatos', to: 'users#index_candidatos', as: 'index_candidatos'
  get '/entidades_destaque', to: 'users#index_entidades_destaque', as: 'index_entidades_destaque'
  get '/candidatos_destaque', to: 'users#index_candidatos_destaque', as: 'index_candidatos_destaque'

  get '/novo_candidato' , to:'users#novo_candidato'
  post '/novo_candidato' , to:'users#create'
  
  get '/nova_entidade' , to:'users#nova_entidade'
  post '/nova_entidade' , to:'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/users/:id/edit', to: 'users#update'
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'

  resources :oferta
  post '/oferta/new', to: 'oferta#create'
  get '/ofertas', to: 'oferta#index', as: 'index_ofertas'
  get '/ofertas_destaque', to: 'oferta#index_destaque', as: 'index_ofertas_destaque'
  put '/ofertas/:id/mudar_estado', to: 'oferta#mudar_estado', as: 'oferta_estado'

  resources :relationships, only: [:create, :destroy]
  resources :oferta_relationships, only: [:create, :destroy]
  
  resources :noticias
  post '/noticias/new', to: 'noticias#create'
  delete '/noticias/:id', to: 'noticias#destroy', as: 'noticias_delete'
  get '/noticias', to: 'noticias#index', as: 'index_noticias'

  get '/backoffice' ,to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/noticias', to: 'backoffice#index_noticias'

  get '/backoffice/noticias/:id', to: 'backoffice#show_noticia', as: 'backoffice_show_noticia'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  
  get '/backoffice/noticias/:id/edit', to:'backoffice#edit_noticias', as: 'backoffice_edit_noticias'
  patch '/backoffice/noticias/:id/edit', to:'noticias#update', as: 'backoffice_update_noticias'

  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'


  resources :backoffice
  resources :newsletters
  resources :password_resets, only: [:new, :create, :edit, :update]
  

end

app/controllers/oferta_controller.rb
class OfertaController < ApplicationController

    before_action :logged_in_user, only: [:edit, :destroy, :create, :update, :mudar_estado]
    before_action :entidade_oferta, only: [:edit, :update, :mudar_estado]

    def index
        @ofertas = Ofertum.order(created_at: :desc)
        filtering_params(params).each do |key, value|
          @ofertas = @ofertas.public_send(key,value) if value.present?
        end
        @ofertas =  @ofertas.paginate(page:params[:page], per_page: 8)
    end

    def index_destaque
        @ofertas = Ofertum.destaque.order(created_at: :desc)
        filtering_params(params).each do |key, value|
          @ofertas = @ofertas.public_send(key,value) if value.present?
        end
        @ofertas =  @ofertas.paginate(page:params[:page], per_page: 8)
        render 'index'
    end

    def new
        @oferta = Ofertum.new
        @user = current_user
    end

    def show
        @oferta = Ofertum.find(params[:id])
        @candidatos = @oferta.candidatos.paginate(page:params[:page], per_page: 2)
        @ofertas_atividade = Ofertum.all.where('atividade_profissional like ? AND id != ?', @oferta.atividade_profissional, @oferta.id).limit(2)
    end

    def create
        @user = current_user
        @offer = @user.ofertum.build(oferta_params)
        if @offer.save
            flash[:success] = "Oferta guardada com Sucesso!"
            redirect_to oferta_path
        else
            render 'new'
        end
    end

    def edit
        @oferta = Ofertum.find(params[:id])
        @user = @oferta.user
    end

    def update
        @oferta = Ofertum.find(params[:id])
        @user = @oferta.user
        @oferta = @user.ofertum.find(params[:id])
        if @oferta.update_attributes(oferta_params)
          flash[:success] = "Oferta atualizada!"
          redirect_to @oferta
        else
          render 'edit'
        end
    end

    def mudar_estado
        @oferta = Ofertum.find(params[:id])
        @user = @oferta.user

        @oferta.mudar_estado
        flash[:success] = "Estado atualizado!"
        redirect_to @oferta
    end

    private

    def oferta_params
        params.require(:ofertum).permit(:titulo, :data_inicio, :data_fim, :descricao,
                                    :salario, :tipo_contrato, :atividade_profissional, :ativa, :foto,:destaque )
    end

    def filtering_params(params)
        params.slice(:search,:atividade_profissional)
    end

    def entidade_oferta
        @oferta = Ofertum.find(params[:id])
        redirect_to(root_url) unless current_user?(@oferta.user) || admin_user?(current_user)
      end
    
end

app/helpers/oferta_helper.rb
module OfertaHelper
end

app/views/oferta/_follow.html.erb
<%= form_for(current_user.ofertas_active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :oferta_id, @oferta.id %></div>
    <%= f.submit "Candidatar-me", class: "btn btn-default" %>
<% end %>

app/views/oferta/_ofertum.html.erb
<aside>
  <section>
    <div class="col-md-3">
      <% if ofertum.foto.attached? %>
        <%= image_tag ofertum.display_image , style:'width:100%' %>
      <% else %>
        <%= image_tag 'default_oferta.png' , style:'width:100%' %>
       <% end %>
    </div>
    <div class="col-md-9">
      <p>
        <%= link_to ofertum.titulo, ofertum %><br>
        <%= ofertum.data_inicio %> até <%= ofertum.data_fim %><br>
        <%= ofertum.user.name %><br>
        <%= raw ofertum.descricao %>
      </p>
    </div>
    <div class="col-md-12" style="min-height: 40px">
      <% if logged_in? %>
          <% unless current_page?(root_path)%>

            <% if admin_user?(current_user) || current_user?(ofertum.user) %>
              <% if current_page?(user_path(current_user)) %>
                <% if ofertum.ativa %>
                  <%= link_to "Editar", edit_ofertum_path(ofertum), class: 'btn btn-default' %>
                  <%= link_to "Desativar", oferta_estado_path(ofertum.id),  method: :put,class: 'btn btn-default' %>
                <% else %>
                  <%= link_to "Reativar", oferta_estado_path(ofertum.id), method: :put, class: 'btn btn-default' %>
                <% end %>
              <% else %>

                <%= link_to "Editar", edit_ofertum_path(ofertum), class: 'btn btn-default' %>
                <% if ofertum.ativa %>
                  <%= link_to "Desativar", oferta_estado_path(ofertum.id), method: :put, class: 'btn btn-default' %>
                <% else %>
                  <%= link_to "Reativar", oferta_estado_path(ofertum.id), method: :put, class: 'btn btn-default' %>
                <% end %>

              <% end %>

            <% end %>
          <% end %>

          <% unless current_page?(root_path) || current_page?(user_path(current_user)) %>
            <% if ofertum.ativa && current_user.tipo == 'candidato'  %>
              <div class="col-md-6">
                <% @oferta = ofertum %>
                <% if current_user.candidato_oferta?(ofertum) %>
                    <%= render 'oferta/unfollow' %>
                <% else %>
                    <%= render 'oferta/follow' %>
                <% end %>
              </div>
            <% end %>
          <% end %>
      <% end %>
    </div>
  </section>
</aside>

app/views/oferta/_unfollow.html.erb
<%= form_for(current_user.ofertas_active_relationships.find_by(oferta_id: @oferta.id),
             html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Retirar Candidatura", class: "btn btn-default" %>
<% end %>

app/views/oferta/edit.html.erb
<% provide(:title, 'Editar Oferta ') %>

<aside class="col-md-12 user_info_avatar">
  <section>
    <h1> Editar Oferta </h1>
  </section>
</aside>
<%= render 'layouts/form_oferta' %>

app/views/oferta/index.html.erb
<% provide(:title, 'Ofertas') %>
<div class="row">
  <aside class="col-md-4">
    <h3>Ofertas</h3>
  </aside>
</div>
<div class="row">
  <aside>
    <%= form_for oferta_path, method: 'get' do %>
        <div class="col-md-3">
          <%= text_field_tag :search, params[:search], placeholder: 'Pesquisa', class: 'form-control' %>
        </div>
        <div class="col-md-3">
          <% field_array = Ofertum.all.distinct.pluck(:atividade_profissional) %>
          <%= select_tag(:atividade_profissional , options_for_select(field_array,params[:atividade_profissional]),{include_blank: 'Atividade profissional...', :onChange => "javascript: this.form.submit();", class: 'form-control'}) %>
        </div>
    <% end %>
  </aside>
</div>

<div class="row">
  <% @ofertas.each do |offer|  %>
      <div class="col-md-6">
        <%= render offer %>
      </div>
  <% end %>

</div>
<%= will_paginate(@ofertas) %>

app/views/oferta/new.html.erb
  <% provide(:title, 'Inserir | Oferta ') %>

<aside class="col-md-12 user_info_avatar">
  <section>
    <h1> Inserir Oferta </h1>
  </section>
</aside>

<%= render 'layouts/form_oferta' %>

app/views/oferta/show.html.erb
<aside class="col-md-12 user_info_avatar">
  <section>
    <h1>
      <%= @oferta.titulo %>
    </h1>
  </section>
</aside>
<aside class="col-md-2 user_info_avatar">
  <section>
    <% if @oferta.foto.attached? %>
        <%= image_tag @oferta.display_image , style:'width:100%' %>
    <% else %>
        <%= image_tag 'default_oferta.png' , style:'width:100%' %>
    <% end %>
  </section>
  <% if logged_in? %>

      <% if current_user.tipo == 'candidato' %>
          <% if current_user.candidato_oferta?(@oferta) %>
              <%= render 'oferta/unfollow' %>
          <% else %>
              <%= render 'oferta/follow' %>
          <% end %>
      <% end %>

      <% if admin_user?(current_user) || current_user?(@oferta.user) %>
        <%= link_to "Editar", edit_ofertum_path, class: 'btn btn-default' %>
      <% end %>

  <% end %>
</aside>
<aside class="col-md-10">
  <section class="user_edit">
    <p> <%= raw @oferta.descricao %> </p>
    <p><%= @oferta.data_inicio %> até <%= @oferta.data_fim %> </p>
    <p><strong>Empresa</strong></p>
    <p><%= link_to @oferta.user.name, user_path(@oferta.user.id) %></p>
    <p><strong>Actividade Profissional</strong></p>
    <p><%= @oferta.atividade_profissional %></p>
    <p><strong>Tipo de Contrato</strong></p>
    <p><%= @oferta.tipo_contrato %></p>
    <p><strong>Salário</strong></p>
    <p><%= @oferta.salario %></p>
  </section>
</aside>

<% if current_user?(@oferta.user) %>
  <% if @candidatos.any? %>
    <div class="row">
      <aside class="col-md-6">
        <section>
          <h1>
            Candidatos
          </h1>
          <%= render @candidatos %>
        </section>
      </aside>
    </div>
  <% end %>
<% else %>
  <% if @ofertas_atividade.any? %>
    <div class="row">
      <aside class="col-md-6">
        <section>
          <h1>
            Outras ofertas na mesma área
          </h1>
          <%= render @ofertas_atividade %>
        </section>
      </aside>
    </div>
  <% end %>
<% end %>

<div class="row">
</div>