config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get  '/sobre',   to: 'static#about'
  get  '/contactos',   to: 'static#contacts'

  resources :users do
    member do
      get :following, :followers,:ofertas, :candidatos
    end
  end

  get 'signup', to: 'users#new'

  get '/entidades', to: 'users#index_entidades', as: 'index_entidades'
  get '/candidatos', to: 'users#index_candidatos', as: 'index_candidatos'
  get '/entidades_destaque', to: 'users#index_entidades_destaque', as: 'index_entidades_destaque'
  get '/candidatos_destaque', to: 'users#index_candidatos_destaque', as: 'index_candidatos_destaque'

  get '/novo_candidato' , to:'users#novo_candidato'
  post '/novo_candidato' , to:'users#create'
  
  get '/nova_entidade' , to:'users#nova_entidade'
  post '/nova_entidade' , to:'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/users/:id/edit', to: 'users#update'
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'

  resources :oferta
  post '/oferta/new', to: 'oferta#create'
  get '/ofertas', to: 'oferta#index', as: 'index_ofertas'
  get '/ofertas_destaque', to: 'oferta#index_destaque', as: 'index_ofertas_destaque'
  put '/ofertas/:id/mudar_estado', to: 'oferta#mudar_estado', as: 'oferta_estado'

  resources :relationships, only: [:create, :destroy]
  resources :oferta_relationships, only: [:create, :destroy]
  
  resources :noticias
  post '/noticias/new', to: 'noticias#create'
  delete '/noticias/:id', to: 'noticias#destroy', as: 'noticias_delete'
  get '/noticias', to: 'noticias#index', as: 'index_noticias'

  get '/backoffice' ,to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/noticias', to: 'backoffice#index_noticias'

  get '/backoffice/noticias/:id', to: 'backoffice#show_noticia', as: 'backoffice_show_noticia'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  
  get '/backoffice/noticias/:id/edit', to:'backoffice#edit_noticias', as: 'backoffice_edit_noticias'
  patch '/backoffice/noticias/:id/edit', to:'noticias#update', as: 'backoffice_update_noticias'

  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'


  resources :backoffice
  resources :newsletters
  resources :password_resets, only: [:new, :create, :edit, :update]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contactos", contactos_path  %></li>
        <li><%= link_to "Sobre", sobre_path %></li>
    </ul>
    <p> Bolsa de Emprego - Projeto WireMaze </p>
</footer>

app/views/layouts/_form_atividade.html.erb
<div class="col-md-3">
  <%= f.input :cv, label: "Currículo",class:'form-control', error:false %>
</div>

<div class="col-md-3 col-md-offset-3">
  <%= f.input :area_profissional, label: "Atividade Profissional", collection: (['Engenharia', 'Letras', 'Saúde', 'Desporto']) , class:"form-control",error: false%>
</div>

<div class="col-md-12">
  <h3>Habilitações Literárias</h3>
  <%= f.text_area :habilitacoes_literarias, label: "Habilitações Literárias", placeholder: 'Percurso académico, habilitações, etc.' , class:"form-control tinymce",error: false%>
</div>

<div class="col-md-2">
  <%= f.input :nivel_habilitacoes, label: "Nível de Habilitações", collection: (['Secundário','Licenciatura','Mestrado','Doutoramento']) , class:"form-control",error: false%>
</div>

<div class="col-md-12">
  <h3>Experiência Profissional</h3>
  <%= f.text_area :experiencia_profissional, label: "Experiência Profissional" , class:"form-control tinymce",error: false%>
</div>

<div class="col-md-2">
  <%= f.input :situacao_profissional, label: "Situação Profissional" ,collection: (['Empregado','Desempregado']), class:"form-control" ,error: false%>
</div>

app/views/layouts/_form_edicao_backoffice.html.erb
<div>
      <div id="new_info">
        <div class="row">
          <div class="col-md-6 ">
            <%= f.input :name,label: "Nome" %>
          </div>
          <div class="col-md-6">
          <%= f.input :tipo, label: "Tipo", collection: (['admin', 'candidato', 'entidade']) , class:"form-control",error: false%>
          </div>
        </div>
        <div class="row">

          <div class="col-md-6 ">
            <%= f.input :email,label: "Email" %>
          </div>

          <div class="col-md-6">
                <div class="checkbox">
                    <%= f.input :activated, inline_label: "Ativo" %>
                </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="checkbox">
              <%= f.input :destaque, inline_label: "Destaque" %>
            </div>
          </div>
          <div class="col-md-2">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
          <div class="col-md-2">
            <%= link_to "Cancelar", backoffice_users_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_form_edicao_noticias.html.erb
<%= simple_form_for @noticia,html:{multipart: true }, url: backoffice_update_noticias_path  do |f| %>
    <div>
      <div id="new_info">
        <div class="row">
          <div class="col-md-6 ">
            <%= f.input :titulo, label: "Título" %>
          </div>
          <div class="col-md-6">
            <%= f.date_field :data, label: "Data",  class: 'form-control' %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h3>Sumário</h3>
            <%= f.text_area :sumario, class:'tinymce' %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h3>Descrição</h3>
            <%= f.text_area :descricao , class:'tinymce'%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            <%= f.input :foto, as: :file, label: "Foto" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <h5><strong>Destaque</strong></h5>
            <br>
            <div class="checkbox">
              <%= f.input :destaque, inline_label: "Sim" %>
            </div>
          </div>
          <div class="col-md-2 col-md-offset-2">
            <h5><strong>Activa</strong></h5>
            <br>
            <div class="checkbox ">
              <%= f.input :ativa, inline_label: "Sim" %>
            </div>

          </div>
        </div>
      </div>
      <div class="row" style="margin-top: 20px;">
        <div class="col-md-2">
          <%= f.button :submit, class: 'btn btn-primary' %>

        </div>
        
      </div>
    </div>
<% end %>

app/views/layouts/_form_edicao_password_backoffice.html.erb
<%= simple_form_for @user, url: backoffice_edit_user_password_path do |f| %>
    <div class="row">
      <div class="col-md-6 ">
        <%= f.label :name, "Nome" %>
        <p> <%= @user.name %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 ">
        <%= f.input :password, label: "Password" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 ">
        <%= f.input :password_confirmation, label: "Confirmação da Password" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
      <div class="col-md-2">
        <%= link_to "Cancelar", backoffice_users_path, class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/layouts/_form_info_login.html.erb
<div class="row" >
  <div class="col-md-6">
    <%= f.input :email , class:"form-control",error: false%>
  </div>
</div>
<div class="row">
  <% if params[:data] == 'reset_password' %>
      <div class="col-md-6">
        <%= f.input :current_password, label: "Password Atual", class:"form-control",error: false %>
      </div>
  <% end %>
</div>
<div class="row">
  <div class="col-md-6">
    <%= f.input :password , class:"form-control",error: false%>
  </div>
  <div class="col-md-6">
    <%= f.input :password_confirmation, label: "Confirmação Password", class:"form-control",error: false %>
  </div>
</div>

app/views/layouts/_form_info_pessoal.html.erb
<div class="row">
  <div class="col-md-6 ">
    <%= f.input :name, label: "Nome" , class:"form-control",error: false%>
  </div>
  <div class="col-md-3">
    <%= f.input :foto, as: :file, label: "Fotografia", error:false %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3>Morada</h3>
    <%= f.text_area :morada, as: :text, label: "Morada" , class:"form-control tinymce",error: false %>
  </div>
  <div class="col-md-2">
    <%= f.input :codigo_postal, label: "Código Postal", class:"form-control" ,error: false%>
  </div>
  <div class="col-md-2 col-md-offset-4">
    <%= f.input :localidade, label: "Localidade", class:"form-control",error: false %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <%= f.input :telefone, label: "Telefone" , class:"form-control",error: false%>
  </div>
  <div class="col-md-2">
    <%= f.input :telemovel, label: "Telemóvel" , class:"form-control",error: false%>
  </div>
  <div class="col-md-6 col-md-offset-2">
    <%= f.input :pagina, label: "Página Pessoal" , class:"form-control",error: false%>
  </div>
</div>

app/views/layouts/_form_noticias.html.erb
<%= simple_form_for @noticia,html:{multipart: true }, url: noticias_new_path  do |f| %>
    <div>
      <div id="new_info">
        <div class="row">
          <div class="col-md-6 ">
            <%= f.input :titulo, label: "Título" %>
          </div>
          <div class="col-md-6">
            <%= f.date_field :data, label: "Data",  class: 'form-control' %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h3>Sumário</h3>
            <%= f.text_area :sumario, class:'tinymce' %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h3>Descrição</h3>
            <%= f.text_area :descricao , class:'tinymce'%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            <%= f.input :foto, as: :file, label: "Foto" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <h5><strong>Destaque</strong></h5>
            <br>
            <div class="checkbox">
              <%= f.input :destaque, inline_label: "Sim" %>
            </div>
          </div>
          <div class="col-md-2 col-md-offset-2">
            <h5><strong>Activa</strong></h5>
            <br>
            <div class="checkbox ">
              <%= f.input :ativa, inline_label: "Sim" %>
            </div>

          </div>
        </div>
      </div>
      <div class="row" style="margin-top: 20px;">
        <div class="col-md-2">
          <%= f.button :submit, class: 'btn btn-primary' %>

        </div>
        
      </div>
    </div>
<% end %>

app/views/layouts/_form_oferta.html.erb
<%= simple_form_for @oferta, html: { multipart: true} do |f| %>
    <div>
      <div id="new_info">
        <div class="row">
          <div class="col-md-6 ">
            <%= f.input :titulo, label: "Título" %>
          </div>
          <div class="col-md-3">
            <%= f.label :data_inicio, "Data Início:" %>
            <%= f.date_field :data_inicio, class: 'form-control' %>

          </div>

          <%= f.hidden_field :user , value: current_user %>

          <div class="col-md-3">
            <%= f.label :data_fim, "Data Fim: "%>
            <%= f.date_field :data_fim, class: 'form-control' %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h3> Descrição </h3>
            <%= f.text_area :descricao, class:'tinymce', label: "Descrição" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            <%= f.input :foto, as: :file, label: "Foto" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= f.label "Empresa" %>
            <p><%= link_to @user.name, @user %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <%= f.input :atividade_profissional, label: "Atividade Profissional",collection: (['Engenharia', 'Letras', 'Saúde', 'Desporto']) %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">

            <%= f.input :tipo_contrato, label: "Tipo de Contrato", collection: (['Full-Time','Part-Time']) %>
          </div>

          <div class="col-md-4 col-md-offset-2">
            <%= f.input :salario,label: "Salário", collection: (['Salário Mínimo','600€-1500€','1500€-2000€','2000€-']) %>
          </div>
        </div>

        <div class="row">

            <div class="col-md-2">
              <h5><strong>Activa</strong></h5>
              <br>
              <div class="checkbox">
                <p>
                  <%= f.input :ativa, inline_label: 'Sim' %>
                </p>
              </div>
            </div>

            <div class="col-md-2">
              <h5><strong>Destaque</strong></h5>
              <br>
              <div class="checkbox">
                <p>
                  <%= f.input :destaque, inline_label: 'Sim' %>
                </p>
              </div>
            </div> 
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-2">
          <%= f.button :submit, 'Criar/Editar oferta',class: "btn btn-primary" %>
        </div>
      </div>
      
    </div>
<% end %>

app/views/layouts/_form_registo_backoffice.html.erb
<div>
      <div id="new_info">
        <div class="row">
          <div class="col-md-6 ">
            <%= f.input :name,label: "Nome" %>
          </div>
          <div class="col-md-6">
          <%= f.input :tipo, label: "Tipo", collection: (['admin', 'candidato', 'entidade']) , class:"form-control",error: false%>
          </div>
        </div>
        <%= render 'layouts/form_info_login', :f => f %>
        <div class="row">

          <div class="col-md-4">
              <div class="checkbox">
                  <%= f.input :activated, inline_label: "Ativo" %>
              </div>
          </div>

          <div class="col-md-4">
              <div class="checkbox">
                  <%= f.input :destaque, inline_label: "Destaque" %>
              </div>
          </div>

          <div class="col-md-2">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
          <div class="col-md-2">
            <%= link_to "Cancelar", backoffice_users_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_form_registo_candidato.html.erb
<%= simple_form_for @user, html: {multipart: true}, url: novo_candidato_path  do |f| %>
    <%= render 'shared/error_messages' %>
    <%= render 'layouts/form_info_login', :f => f %>

    <div id="info_candidato" class="profile">
        <%= render 'layouts/form_info_pessoal', :f => f %>
        <div class="row">
            <div class="col-md-2">
                <%= f.date_field :data_nascimento, label:"Data Nascimento", class:"form-control" ,error: false%>
            </div>
            <div class="col-md-3 col-md-offset-4">
                <%= f.input :bilhete_identidade,label: "Nº Cartão do Cidadão" , class:"form-control" ,error: false%>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <h3>Apresentação</h3>
                <%= f.text_area :apresentacao, label:  "Apresentação", class:"tinymce" %>
            </div>
        </div>

        <div class="row">
            <%= render 'layouts/form_atividade', :f => f %>
        </div>
        <%= f.hidden_field :tipo, value: 'candidato' %>
        
        <div class="row" style="margin:5% 0%">
          <div class="col-md-6">
            <div class="checkbox">
              <%= f.input :newsletter, inline_label: "Newsletter" %>
            </div>
          </div>
        </div>

    </div>

    <div class="col-md-2">
      <%= f.button :submit, "Registar Candidato",class: "btn btn-primary" %>
    </div>
<% end %>

<script type="text/javascript">
  $('#user_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('O tamanho máximo é de 5MB. Por favor escolha uma imagem mais pequena.');
    }
  });
  $('#user_curriculum').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('O tamanho máximo é de 5MB. Por favor escolha um formato do currículo mais pequeno.');
    }
  });
  
  $(".datepicker").datepicker();

</script>

app/views/layouts/_form_registo_entidade.html.erb
<%= simple_form_for @user, html: {multipart: true}, url: nova_entidade_path do |f| %>
    <%= render 'shared/error_messages' %>
    <%= render 'layouts/form_info_login', :f => f %>

    <div id="info_entidade" class="profile">
        <%= render 'layouts/form_info_pessoal', :f => f %>

        <div class="row">
            <div class="col-md-2">
            <%= f.input :bilhete_identidade, label: "NIF" %>
            </div>
        </div>
        
        <%= f.hidden_field :tipo, value: 'entidade' %>

        <div class="row">
            <div class="col-md-2 col-md-offset-3">
                <%= f.input :area_profissional, label: "Atividade Profissional", collection: (['Engenharia', 'Letras', 'Saúde', 'Desporto']) , class:"form-control",error: false%>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <h3>Apresentação</h3>
                <%= f.text_area :apresentacao, label:  "Apresentação", class:"tinymce" %>
            </div>
        </div>

        <div class="row" style="margin:5% 0%">
          <div class="col-md-6">
            <div class="checkbox">
              <%= f.input :newsletter, inline_label: "Receber Newsletter" %>
            </div>
          </div>
        </div>
        
        

        <div class="col-md-2">
            <%= f.button :submit, "Registar Entidade", class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

<script type="text/javascript">
  $('#user_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('O tamanho máximo é de 5MB. Por favor escolha uma imagem mais pequena.');
    }
  });


</script>

app/views/layouts/_head.html.erb
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
            <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag "application" %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "Bolsa de Emprego", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-left">
                
                <% if logged_in? && admin_user?(@current_user)  %>
                    <% if request.fullpath.include?('backoffice')  %>
                        <li><%= link_to "Frontoffice", root_path %></li>
                        <li><%= link_to "Utilizadores",   backoffice_users_url %></li>
                        <li><%= link_to "Notícias", backoffice_noticias_url  %></li>
                    <% else %>
                        <li><%= link_to "Backoffice", backoffice_path %></li>
                        
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Ofertas <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Todas", index_ofertas_path %></li>
                                <li><%= link_to "Em destaque", index_ofertas_destaque_path %></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Candidatos <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Todos", index_candidatos_path %></li>
                                <li><%= link_to "Em destaque", index_candidatos_destaque_path %></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Entidades <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Todos", index_entidades_path %></li>
                                <li><%= link_to "Em destaque", index_entidades_destaque_path %></li>
                            </ul>
                        </li>

                        
                        <li><%= link_to "Notícias", index_noticias_path %></li>
                    <% end %>
                <% else %>
                    <li><%= link_to "Home", root_path %></li>
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Ofertas <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Todas", index_ofertas_path %></li>
                            <li><%= link_to "Em destaque", index_ofertas_destaque_path %></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Candidatos <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Todos", index_candidatos_path %></li>
                            <li><%= link_to "Em destaque", index_candidatos_destaque_path %></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Entidades <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Todos", index_entidades_path %></li>
                            <li><%= link_to "Em destaque", index_entidades_destaque_path %></li>
                        </ul>
                    </li>

                    <li><%= link_to "Notícias", index_noticias_path %></li>
                <% end %>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                    <% if admin_user?(@current_user) %>
                        <li> <%= link_to "Logout", logout_path, method: :delete %> </li>
                    <% else %>
                        <li><%= link_to @current_user.name,  user_path(current_user, perfil:'true') %></li>
                        <li><%= link_to 'Detalhes',  user_path(current_user) %></li>
                        <li> <%= link_to "Logout", logout_path, method: :delete %> </li>
                    <% end %>
                <% else %>
                    <li><%= link_to "Registo", signup_path %></li>
                    <li><%= link_to "Log in", login_path  %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>